#!/usr/bin/env python3
"""Builds apis/postgrescluster/composition.yaml from composition.tmpl.yaml.

Embeds two vendored sources into the function-go-templating template:

  src/dashboards/cnpg-cluster.json    -> the #@DASHBOARD_JSON@ marker
  src/alerts/cnpg-cluster-rules.yaml  -> the #@ALERT_RULES@ marker

Both contain literal {{ ... }} (Grafana legend formats, Prometheus alert
templating) that must survive function-go-templating's own Go-template pass,
so every {{ / }} is escaped as {{"{{"}} / {{"}}"}}. Placeholders are then
swapped for template expressions so each PostgresCluster gets its own
dashboard title/uid/preselected variables and cluster-scoped alert rules.

  python3 hack/generate.py          # write composition.yaml
  python3 hack/generate.py --check  # exit 1 if composition.yaml is stale
"""
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
API = ROOT / "apis" / "postgrescluster"
TEMPLATE = API / "composition.tmpl.yaml"
OUTPUT = API / "composition.yaml"
DASHBOARD = ROOT / "src" / "dashboards" / "cnpg-cluster.json"
RULES = ROOT / "src" / "alerts" / "cnpg-cluster-rules.yaml"

# Placeholders used in the vendored sources / injected below.
CLUSTER, NAMESPACE, UID = "zzclusterzz", "zznamespacezz", "zzuidzz"
SUBST = {
    CLUSTER: "{{ $name }}",
    NAMESPACE: "{{ $namespace }}",
    UID: "{{ $dashUid }}",
}

HEADER = """\
# GENERATED by hack/generate.py from composition.tmpl.yaml -- DO NOT EDIT.
# Apply with `kubectl apply --server-side` (the embedded dashboard is too big
# for the client-side last-applied-configuration annotation).
"""


def escape(text: str) -> str:
    """Escape Go-template delimiters so they render literally.

    Every maximal run of 2+ braces becomes one Go string literal, e.g.
    `{{` -> `{{"{{"}}` and `{}}` -> `{{"{}}"}}`. Escaping whole runs (not
    just `{{`/`}}` pairs) matters for compact JSON like `"text":{}}`, where
    a pair-wise escape would leave a literal `{` right before the inserted
    `{{` and the lexer would read `{{{` as an action.
    """
    return re.sub(r"[{}]{2,}", lambda m: '{{"' + m.group() + '"}}', text)


def substitute(text: str) -> str:
    for placeholder, expr in SUBST.items():
        text = text.replace(placeholder, expr)
    return text


def dashboard() -> str:
    d = json.loads(DASHBOARD.read_text())
    d["title"] = f"CloudNativePG / {NAMESPACE} / {CLUSTER}"
    d["uid"] = UID
    for var in d["templating"]["list"]:
        if var["name"] == "namespace":
            var["current"] = {"selected": True, "text": NAMESPACE, "value": NAMESPACE}
        elif var["name"] == "cluster":
            var["current"] = {"selected": True, "text": CLUSTER, "value": CLUSTER}
    # Compact: Crossplane keeps a full copy of the Composition in every
    # CompositionRevision; the readable source stays in src/dashboards/.
    return substitute(escape(json.dumps(d, separators=(",", ":"))))


class _Dumper(yaml.SafeDumper):
    pass


_Dumper.add_representer(
    str,
    lambda dumper, data: dumper.represent_scalar(
        "tag:yaml.org,2002:str", data, style="|" if "\n" in data else None
    ),
)


def alert_rules() -> str:
    """One YAML list item per rule, each wrapped in an excludeRules guard."""
    rules = yaml.safe_load(RULES.read_text())
    out = []
    for rule in rules:
        body = yaml.dump([rule], Dumper=_Dumper, sort_keys=False, width=1000).rstrip("\n")
        name = rule["alert"]
        out.append(f'{{{{- if not (has "{name}" $excludeRules) }}}}')
        out.append(substitute(escape(body)))
        out.append("{{- end }}")
    return "\n".join(out)


def render() -> str:
    blocks = {"#@DASHBOARD_JSON@": dashboard(), "#@ALERT_RULES@": alert_rules()}
    lines = []
    for line in TEMPLATE.read_text().splitlines():
        marker = line.strip()
        if marker in blocks:
            indent = line[: len(line) - len(line.lstrip())]
            lines.extend(indent + l if l else "" for l in blocks[marker].splitlines())
        else:
            lines.append(line)
    # Drop the template's first comment paragraph (instructions for editing
    # the template itself, up to the first bare "#"); HEADER replaces it.
    if "#" in lines:
        lines = lines[lines.index("#") + 1 :]
    return HEADER + "\n".join(lines) + "\n"


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        if not OUTPUT.exists() or OUTPUT.read_text() != content:
            print(f"{OUTPUT.relative_to(ROOT)} is stale: run `make generate`", file=sys.stderr)
            return 1
        print(f"{OUTPUT.relative_to(ROOT)} is up to date")
        return 0
    OUTPUT.write_text(content)
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(content) // 1024} KiB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
