"""Generate an observed-state fixture for tests/render: render a case until
nothing new appears, then report every composed object as existing and
healthy (provider-kubernetes Objects through status.atProvider.manifest).

usage: hack/observe.py <api> <case>   (writes tests/render/<api>/observed/<case>.yaml)

Needs the crossplane CLI and a Docker API, like tests/render/run.sh. Health
is what the compositions look for: Namespace Active, Prometheus Available,
Grafana complete/success, Ready=True conditions (CNPG Cluster, Objects),
a provisioned BucketClaim and a granted BucketAccess (COSI), a CronJob
whose last run succeeded.
"""
import copy
import os
import subprocess
import sys
import tempfile

import yaml

api, case = sys.argv[1:3]
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
tests = os.path.join(root, "tests", "render", api)
required = os.path.join(tests, "required", f"{case}.yaml")
if not os.path.exists(required):
    required = os.path.join(tests, "required", "default.yaml")


def healthy(obj):
    obj = copy.deepcopy(obj)
    ready = [{"type": "Ready", "status": "True", "reason": "Available"}]
    kind = obj["kind"]
    if kind == "Namespace":
        obj["status"] = {"phase": "Active"}
    elif kind == "Prometheus":
        obj["status"] = {"conditions": [{"type": "Available", "status": "True"}]}
    elif kind == "Grafana":
        obj["status"] = {"stage": "complete", "stageStatus": "success"}
    elif kind == "Cluster":
        n = obj["spec"]["instances"]
        obj["status"] = {"phase": "Cluster in healthy state", "instances": n, "readyInstances": n,
                         "currentPrimary": f"{obj['metadata']['name']}-1", "conditions": ready}
    elif kind == "Database":
        obj["status"] = {"applied": True}
    elif kind == "BucketClaim":
        obj["status"] = {"bucketName": f"{obj['metadata']['namespace']}-{obj['metadata']['name']}-0f3a", "bucketReady": True}
    elif kind == "BucketAccess":
        obj["status"] = {"accessGranted": True, "accountID": "e2e"}
    elif kind == "CronJob":
        obj["status"] = {"lastScheduleTime": "2026-01-01T00:05:00Z", "lastSuccessfulTime": "2026-01-01T00:05:04Z"}
    return obj


def observe(desired):
    out = []
    for d in desired:
        d = copy.deepcopy(d)
        d["metadata"]["annotations"] = {"crossplane.io/composition-resource-name":
                                        d["metadata"]["annotations"]["crossplane.io/composition-resource-name"]}
        d["metadata"].pop("labels", None)
        d["metadata"].pop("ownerReferences", None)
        d["metadata"].pop("generateName", None)
        if d["kind"] == "Object":
            manifest = healthy(d["spec"]["forProvider"]["manifest"])
            d = {k: d[k] for k in ("apiVersion", "kind", "metadata")}
            d["status"] = {"atProvider": {"manifest": manifest},
                           "conditions": [{"type": "Ready", "status": "True", "reason": "Available"},
                                          {"type": "Synced", "status": "True", "reason": "ReconcileSuccess"}]}
        else:
            d = healthy(d)
            d.pop("spec", None)
        out.append(d)
    return out


observed, seen = [], None
with tempfile.TemporaryDirectory() as tmp:
    obs_path = os.path.join(tmp, "observed.yaml")
    for _ in range(5):
        args = ["crossplane", "render", os.path.join(tests, "xr", f"{case}.yaml"),
                os.path.join(root, "apis", api, "composition.yaml"), os.path.join(root, "install", "functions.yaml"),
                "--xrd", os.path.join(root, "apis", api, "definition.yaml")]
        if os.path.exists(required):
            args.append(f"--required-resources={required}")
        if observed:
            yaml.safe_dump_all(observed, open(obs_path, "w"))
            args.append(f"--observed-resources={obs_path}")
        docs = [d for d in yaml.safe_load_all(subprocess.run(args, check=True, capture_output=True, text=True).stdout) if d]
        xr_kind = yaml.safe_load(open(os.path.join(tests, "xr", f"{case}.yaml")))["kind"]
        desired = [d for d in docs if d["kind"] not in (xr_kind, "Result")]
        keys = sorted(d["metadata"]["annotations"]["crossplane.io/composition-resource-name"] for d in desired)
        observed = observe(desired)
        if keys == seen:
            break
        seen = keys

target = os.path.join(tests, "observed", f"{case}.yaml")
with open(target, "w") as f:
    f.write(f"# Observed state for xr/{case}.yaml: every composed object exists and is healthy.\n"
            f"# Generated by hack/observe.py {api} {case}; regenerate instead of editing.\n")
    yaml.safe_dump_all(observed, f, sort_keys=False)
print(f"wrote {os.path.relpath(target, root)} ({len(observed)} resources)")
